#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - Simulate
    

Simulate_AixLib_Airflow:
    stage: Simulate
    services:
        -  docker
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36  
        - python -V               # Print out python version for debugging
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - model=$(git diff --raw HEAD^1)
        - echo $model >  bin/03_WhiteLists/changedmodels.txt
        - python bin/02_CITests/UnitTests/CheckPackages/validatetest.py -s "AixLib" -p AixLib/package.mo --SimulateExamples -CM
    artifacts:
        when: on_failure
        paths:
            - AixLib/AixLib.Airflow-log.txt
            - AixLib/AixLib.Airflow-Errorlog.txt
        expire_in: 2 day 
    allow_failure: true 
    only:
        variables:
            - $CI_COMMIT_MESSAGE !~ /Correct HTML Code/   

