#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - RegressionTest


Regression_overall_coverage:
    stage: RegressionTest
    before_script:
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py --coverage-only -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
            - AixLib/simulator-dymola.log
        expire_in: 7 day 
    retry:
        max: 2
        when: runner_system_failure
    only:
        - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/    
            
Regressiontest_AixLib_Airflow:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - python -V               # Print out python version for debugging
        - dir
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Airflow --tool dymola -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure
    only:
        - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/    
Regressiontest_AixLib_BoundaryConditions:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - python -V               # Print out python version for debugging
        - dir
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.BoundaryConditions --tool dymola -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure
    only:
        - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/    

Regressiontest_AixLib_Controls:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - python -V               # Print out python version for debugging
        - dir
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Controls --tool dymola -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure       
    only:
        - external_pull_requests   
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/        

#Regressiontest_AixLib_Electrical:
#      stage: RegressionTest
#      services:
#        -  docker
#      before_script:
#        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
#        - export PIP_CACHE_DIR="/opt/cache/pip"
#        - source activate python36
#        - python -V               # Print out python version for debugging
#        - dir
#        - export PYTHONIOENCODING=utf-8 # just in case
#      script:
#        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Electrical --tool dymola -DS ${DymolaVersion}
#      artifacts:
#        when: on_failure
#        paths:
#          - AixLib/simulator-dymola.log
#      retry:
#        max: 2
#        when: runner_system_failure       

#Regressiontest_AixLib_FastHVAC:
#      stage: RegressionTest
#      services:
#        -  docker
#      before_script:
#        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
#        - export PIP_CACHE_DIR="/opt/cache/pip"
#        - source activate python36
#        - python -V               # Print out python version for debugging
#        - dir
#        - export PYTHONIOENCODING=utf-8 # just in case
#      script:
#        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.FastHVAC --tool dymola -DS ${DymolaVersion}
#      artifacts:
#        when: on_failure
#       paths:
#          - AixLib/simulator-dymola.log
#      retry:
#        max: 2
 #       when: runner_system_failure  

Regressiontest_AixLib_Fluid:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - python -V               # Print out python version for debugging
        - dir
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Fluid --tool dymola -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure  
    only:
        - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/        

Regressiontest_AixLib_Media:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - python -V               # Print out python version for debugging
        - dir
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Media --tool dymola -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure  
    only:
        - external_pull_requests  
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/        

Regressiontest_AixLib_Systems:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - python -V               # Print out python version for debugging
        - dir
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.Systems --tool dymola -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure          
    only:
        - external_pull_requests
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/        

Regressiontest_AixLib_ThermalZones:
    stage: RegressionTest
    before_script:
        - Xvfb :77 -extension RANDR -extension GLX & export DISPLAY=:77.0 &&
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate python36
        - python -V               # Print out python version for debugging
        - dir
        - pip install --upgrade git+https://github.com/MichaMans/BuildingsPy@testexamplescoverage
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - cd AixLib && python ../bin/02_CITests/UnitTests/runUnitTests.py -n 2 --batch --single-package AixLib.ThermalZones --tool dymola -DS ${DymolaVersion}
    artifacts:
        when: on_failure
        paths:
          - AixLib/simulator-dymola.log
        expire_in: 7 day
    retry:
        max: 2
        when: runner_system_failure        
    only:
        - external_pull_requests 
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~  /Correct HTML Code/         
          
