# configuration file for automatic issue branch creation
branchName: 'Issue${issue.number}_${issue.title}'
silent: false
autoCloseIssue: true
gitSafeReplacementChar: '_'
defaultBranch: 'development'

branches:
  - label: question
    skip: true