within AixLib.PlugNHarvest.Components.InternalGains.Facilities.Lights;
model LightingForZone
  "Model for lighting in a zone, considering electrical and thermal effects "
  extends
    PlugNHarvest.Components.InternalGains.BaseClasses.PartialElectricalEquipment;

  parameter Modelica.SIunits.Area zoneArea = 100 "zone area";
  parameter Real spPelSurface(unit = "W/m2") =  22 "specific Pel per surface area for type of light source";
  parameter Real coeffThermal = 0.9 "coeff = Pth/Pel";
  parameter Real coeffRadThermal = 0.89 "coeff = Pth,rad/Pth";
  parameter Real emissivityLamp =  0.98 "emissivity of lamp";
  Modelica.Blocks.Sources.Constant AreaofZone(k=zoneArea)
    annotation (Placement(transformation(extent={{-60,20},{-40,40}})));
  Modelica.Blocks.Sources.Constant SpecificElectricalPower(k=spPelSurface)
    "in W/m2 for area"
    annotation (Placement(transformation(extent={{-60,-40},{-40,-20}})));
  Modelica.Blocks.Math.MultiProduct multiProduct(nu=3)
    annotation (Placement(transformation(extent={{-16,-8},{-4,4}})));
  Modelica.Blocks.Math.Gain coeffPthermal(k=coeffThermal)
    annotation (Placement(transformation(extent={{12,14},{24,26}})));
  Modelica.Blocks.Math.Gain coefPth_conv(k=1 - coeffRadThermal)
    annotation (Placement(transformation(extent={{30,34},{38,42}})));
  Modelica.Thermal.HeatTransfer.Sources.PrescribedHeatFlow ConvectiveHeat             annotation(Placement(transformation(extent={{46,28},
            {66,48}})));
  Modelica.Thermal.HeatTransfer.Interfaces.HeatPort_a ConvHeat
    "convective heat connector"                                                            annotation(Placement(transformation(extent={{80,60},
            {100,80}}),                                                                                                                                         iconTransformation(extent={{80,60},
            {100,80}})));
  Modelica.Blocks.Math.Gain coeffOth_rad(k=coeffRadThermal)
    annotation (Placement(transformation(extent={{30,-4},{38,4}})));
  Modelica.Thermal.HeatTransfer.Sources.PrescribedHeatFlow RadiativeHeat                    annotation(Placement(transformation(extent={{46,-10},
            {66,10}})));
  AixLib.Utilities.HeatTransfer.HeatToStar
                                  RadiationConvertor(  A=max(1e-4, zoneArea/30.0), eps=
        emissivityLamp)
    annotation (Placement(transformation(extent={{70,-8},{90,12}})));
  AixLib.Utilities.Interfaces.RadPort RadHeat "radiative heat connector"
    annotation (Placement(transformation(extent={{100,-8},{120,12}}),
        iconTransformation(extent={{80,2},{100,22}})));
equation
  connect(Schedule, multiProduct.u[1])
    annotation (Line(points={{-100,0},{-16,0},{-16,0.8}}, color={0,0,127}));
  connect(AreaofZone.y, multiProduct.u[2]) annotation (Line(points={{-39,30},{-28,
          30},{-28,-2},{-16,-2}}, color={0,0,127}));
  connect(SpecificElectricalPower.y, multiProduct.u[3]) annotation (Line(points=
         {{-39,-30},{-28,-30},{-28,-4.8},{-16,-4.8}}, color={0,0,127}));
  connect(multiProduct.y, Pel) annotation (Line(points={{-2.98,-2},{0,-2},{0,-50},
          {100,-50}}, color={0,0,127}));
  connect(multiProduct.y, coeffPthermal.u) annotation (Line(points={{-2.98,-2},{
          0,-2},{0,20},{10.8,20}}, color={0,0,127}));
  connect(coefPth_conv.y, ConvectiveHeat.Q_flow)
    annotation (Line(points={{38.4,38},{46,38}}, color={0,0,127}));
  connect(ConvectiveHeat.port,ConvHeat)  annotation(Line(points={{66,38},{74,38},
          {74,70},{90,70}},                                                                                 color = {191, 0, 0}, pattern = LinePattern.Solid));
  connect(coeffOth_rad.y, RadiativeHeat.Q_flow)
    annotation (Line(points={{38.4,0},{46,0}}, color={0,0,127}));
  connect(RadiationConvertor.Star,RadHeat)  annotation (Line(
      points={{89.1,2},{110,2}},
      color={95,95,95},
      pattern=LinePattern.Solid));
  connect(coeffPthermal.y, coefPth_conv.u) annotation (Line(points={{24.6,20},{26,
          20},{26,38},{29.2,38}}, color={0,0,127}));
  connect(coeffPthermal.y, coeffOth_rad.u) annotation (Line(points={{24.6,20},{26,
          20},{26,0},{29.2,0}}, color={0,0,127}));
  connect(RadiativeHeat.port, RadiationConvertor.Therm)
    annotation (Line(points={{66,0},{70,0},{70,2},{70.8,2}}, color={191,0,0}));
  annotation (Documentation(info="<html>
<h4>Objective</h4>
<p>The model describes the electrical power consumed by lighting and the thermal power generated by lighting for a certain zone.</p>
<p>The model can be thus used to calculate both the thermal and the electrical load / energy consumption of a building caused by lighting.</p>
<p>The input is a schedule for the lighting and can vary between 0 and 1.</p>
<p>The assumptions as well as exemplary values for the parameters are listed below. </p>
<h4>Assumptions</h4>
<p>The surface of the lamps is assumed as 1/30 of the zone area. The emissivity of the lamps is assumed to be 0.98. Both these values are needed for the calculation of the radiative heat exchange.</p>
<h4>Illuminance requirements according to zone use</h4>
<p>(Source DIN V 18599-10:2016-10, Tables A 1-41)</p>
<table cellspacing=\"0\" cellpadding=\"2\" border=\"1\" width=\"100%\"><tr>
<td><h4>Type of zone</h4></td>
<td><p>Illuminace in lux</p></td>
</tr>
<tr>
<td><p>Office (however many occupants)</p></td>
<td><p>500</p></td>
</tr>
<tr>
<td><p>Meeting room</p></td>
<td><p>500</p></td>
</tr>
<tr>
<td><p>Service hall</p></td>
<td><p>200</p></td>
</tr>
<tr>
<td><p>Retail Food and Non-Food</p></td>
<td><p>300</p></td>
</tr>
<tr>
<td><p>Classroom</p></td>
<td><p>300</p></td>
</tr>
<tr>
<td><p>Auditorium</p></td>
<td><p>500</p></td>
</tr>
<tr>
<td><p>Dormitory</p></td>
<td><p>300</p></td>
</tr>
<tr>
<td><p>Hotel room</p></td>
<td><p>200</p></td>
</tr>
<tr>
<td><p>Canteen</p></td>
<td><p>200</p></td>
</tr>
<tr>
<td><p>Restaurant</p></td>
<td><p>200</p></td>
</tr>
<tr>
<td><p>Kitchen non-residential</p></td>
<td><p>500</p></td>
</tr>
<tr>
<td><p>Kitchen - food preparation, storage</p></td>
<td><p>300</p></td>
</tr>
<tr>
<td><p>Restroom</p></td>
<td><p>200</p></td>
</tr>
<tr>
<td><p>Common room - break room, waiting room</p></td>
<td><p>300</p></td>
</tr>
<tr>
<td><p>Secondary area - cloackroom, storage, archive</p></td>
<td><p>100</p></td>
</tr>
<tr>
<td><p>Corridor</p></td>
<td><p>100</p></td>
</tr>
<tr>
<td><p>Storage</p></td>
<td><p>100</p></td>
</tr>
<tr>
<td><p>Server room</p></td>
<td><p>500</p></td>
</tr>
<tr>
<td><p>Industrial hall - heavy labor standing up</p></td>
<td><p>300</p></td>
</tr>
<tr>
<td><p>Industrial hall - middle labour mainly standing up</p></td>
<td><p>400</p></td>
</tr>
<tr>
<td><p>Industrial hall - simple labour sitting down</p></td>
<td><p>500</p></td>
</tr>
<tr>
<td><p>Spectator area</p></td>
<td><p>200</p></td>
</tr>
<tr>
<td><p>Foyer theater</p></td>
<td><p>300</p></td>
</tr>
<tr>
<td><p>Stage theater</p></td>
<td><p>1000</p></td>
</tr>
<tr>
<td><p>......</p></td>
<td></td>
</tr>
</table>
<p><br><h4>Luminous efficacy for different light sources</h4></p>
<p>(Source: Deliverable 2.2 Shopping malls ineffciencies from Project CommONEnergy: Re-conceptualize shopping malls from consumerism to energy conservation; 2015, page 64 Figure 38)</p>
<table cellspacing=\"0\" cellpadding=\"2\" border=\"1\" width=\"100%\"><tr>
<td><h4>Light source</h4></td>
<td><h4>Luminous efficacy in lm/W</h4></td>
</tr>
<tr>
<td><p>Incandescent lamp</p></td>
<td><p>10-13</p></td>
</tr>
<tr>
<td><p>Halogen lamp</p></td>
<td><p>15-25</p></td>
</tr>
<tr>
<td><p>Compact flourescent lamp</p></td>
<td><p>50-70</p></td>
</tr>
<tr>
<td><p>Flourescent lamp</p></td>
<td><p>70-95 </p></td>
</tr>
<tr>
<td><p>Metal halide lamp</p></td>
<td><p>70-100</p></td>
</tr>
<tr>
<td><p>High pressure sodium vapour lamp</p></td>
<td><p>90-140</p></td>
</tr>
<tr>
<td><p>(O)LED</p></td>
<td><p>80-120</p></td>
</tr>
</table>
<p><br><h4>Conversion from lux to W/m2</h4></p>
<p><br>1 lux = 1 lm / m2</p>
<p>1 W/m2 = 1 lux / (1 lm / W) = Illuminace / Luminous efficacy</p>
<h4>Heat generated by a lighting source</h4>
<p>A lighting source generates optical power and thermal power using electrical power.</p>
<p>The thermal power is split in convective and radiative power.</p>
<p>(Source: http://bigladdersoftware.com/epx/docs/8-0/engineering-reference/page-089.html -&gt; Heat gain from lights)</p>
<table cellspacing=\"0\" cellpadding=\"2\" border=\"1\" width=\"100%\"><tr>
<td><h4>Light source</h4></td>
<td><h4>optical power</h4></td>
<td><h4>thermal convective power</h4></td>
<td><h4>thermal radaitive power</h4></td>
</tr>
<tr>
<td><p>Incandescent lamp</p></td>
<td><p>10&percnt;</p></td>
<td><p>10&percnt;</p></td>
<td><p>80&percnt;</p></td>
</tr>
<tr>
<td><p>Flourescent lamp</p></td>
<td><p>20&percnt;</p></td>
<td><p>20&percnt;</p></td>
<td><p>60&percnt;</p></td>
</tr>
</table>
</html>",
        revisions="<html>
<ul>
<li><i>September, 2017&nbsp;</i> by Ana Constantin:<br>Implemented</li>
</ul>
</html>"), Icon(graphics={
        Ellipse(
          extent={{-52,72},{50,-40}},
          lineColor={255,255,0},
          fillColor={255,255,0},
          fillPattern=FillPattern.Solid),
        Line(
          points={{-24,-56},{22,-56}},
          thickness=1),
        Line(
          points={{-26,-48},{22,-48}},
          thickness=1),
        Line(
          points={{-24,-64},{22,-64}},
          thickness=1),
        Line(
          points={{-24,-72},{22,-72}},
          thickness=1),
        Line(
          points={{-28,-42},{-28,-80},{26,-80},{26,-42}},
          thickness=1),
        Ellipse(
          extent={{-52,72},{50,-40}},
          lineColor={255,255,0},
          fillColor={255,255,0},
          fillPattern=FillPattern.Solid),
        Line(
          points={{-24,-56},{22,-56}},
          thickness=1),
        Line(
          points={{-26,-48},{22,-48}},
          thickness=1),
        Line(
          points={{-24,-64},{22,-64}},
          thickness=1),
        Line(
          points={{-24,-72},{22,-72}},
          thickness=1),
        Line(
          points={{-28,-42},{-28,-80},{26,-80},{26,-42}},
          thickness=1)}));
end LightingForZone;
