language: python
python:
  - "2.7"

cache: pip

notifications:
  email: false

git:
  depth: 10

services:
  - docker

env:
  - TEST_ARG="make test-documentation"


# Install dependencies
# For sphinx, we need to install specific package versions, otherwise
# the html output may have small formatting differences which causes
# the test to fail
install:
  - export PYTHONIOENCODING=UTF8 # just in case
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  - pip install git+https://github.com/lbl-srg/BuildingsPy@master

# Execute tests
script:
  - (cd AixLib/Resources/Scripts/travis && travis_wait 70 $TEST_ARG)
