within AixLib.Fluid.HeatPumps.ModularReversible.Data.TableDataSDF.TableData4DDeltaTEva;
package VCLibPy
  "Package containing links to 4D-SDF tables generated by VCLibPy"
  extends Modelica.Icons.MaterialPropertiesPackage;

end VCLibPy;
