within AixLib.Fluid.HeatPumps.ModularReversible.Data.TableDataSDF.TableData4D;
package VCLibPy_dTEva
  "Package containing links to 4D-SDF tables generated by VCLibPy with variation of temperature difference in evaporator"
  extends Modelica.Icons.MaterialPropertiesPackage;

end VCLibPy_dTEva;
