within ;
package AixLib









  annotation (
  uses(
    Modelica(version="3.2.3"),
    Modelica_Synchronous(version="0.92.2"),
    NcDataReader2(version="2.5.0"),
    SDF(version="0.4.1"),
    Modelica_DeviceDrivers(version="1.7.0")),
  version = "1.0.2",
  conversion(from(
    version="0.3.2",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.3.2_to_0.4.mos",
    version="0.5.0",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.5.0_to_0.5.1.mos",
    version="0.5.2",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.5.2_to_0.5.3.mos",
    version="0.5.3",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.5.3_to_0.5.4.mos",
    version="0.5.4",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.5.4_to_0.5.5.mos",
    version="0.6.0",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.6.0_to_0.7.0.mos",
    version="0.7.3",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.3_to_0.7.4.mos",
    version="0.7.4",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.4_to_0.7.5.mos",
    version="0.7.5",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.5_to_0.7.6.mos",
    version="0.7.6",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.6_to_0.7.7.mos",
    version="0.7.7",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.7_to_0.7.8.mos",
    version="0.7.8",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.8_to_0.7.9.mos",
    version="0.7.9",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.9_to_0.7.10.mos",
    version="0.7.10",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.10_to_0.7.11.mos",
    version="0.7.11",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.11_to_0.7.12.mos",
    version="0.7.12",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.7.12_to_0.8.0.mos",
    version="0.8.0",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.8.0_to_0.8.1.mos",
    version="0.8.1",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.8.1_to_0.8.2.mos",
    version="0.8.2",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.8.2_to_0.8.3.mos",
    version="0.9.1",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.9.1_to_0.9.2.mos",
    version="0.9.2",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.9.2_to_0.9.3.mos",
    version="0.9.3",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.9.3_to_0.9.4.mos",
    version="0.9.4",
                     script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.9.4_to_0.10.0.mos",
    version="0.10.0",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.10.0_to_0.10.1.mos",
    version="0.10.1",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.10.1_to_0.10.2.mos",
    version="0.10.2",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.10.2_to_0.10.3.mos",
    version="0.10.3",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.10.3_to_0.10.4.mos",
    version="0.10.4",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.10.4_to_0.10.5.mos",
    version="0.10.5",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.10.5_to_0.10.6.mos",
    version="0.10.6",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.10.6_to_0.10.7.mos",
    version="0.10.7",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.10.7_to_0.11.0.mos",
    version="0.11.0",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.11.0_to_0.11.1.mos",
    version="0.11.1",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.11.1_to_0.12.0.mos",
    version="0.12.0",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.12.0_to_0.12.1.mos",
    version="1.0.1",
                      script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_1.0.1_to_1.0.2.mos"), from(
      version="1.0.2",
      to="Intermediate",
      change(
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.BaseClasses.ModularBoiler",
            "AixLib.Systems.ModularEnergySystems.Modules.BaseClasses.ModularBoiler_base"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "TSet_Return",
            "TSet_Cold"),
        item=convertClass("AixLib.Systems.HydraulicModules.SimpleConsumer",
            "AixLib.Systems.HydraulicModules.SimpleConsumer_old"),
        item=convertClass(
            "AixLib.Systems.HydraulicModules.SimpleConsumer_wPump",
            "AixLib.Systems.HydraulicModules.SimpleConsumer"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Examples.SimpleConsumer_Pump",
            "AixLib.Systems.ModularEnergySystems.Examples.ModularBoiler"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Examples.ModularBoiler",
            "senTReturn",
            "senTFlow1"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Examples.ModularBoiler",
            "senTFlow",
            "senTReturn"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Examples.ModularBoiler",
            "senTFlow1",
            "senTFlow"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.BaseClasses.ModularBoiler_base",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.BaseClasses.Base_ModBoiler",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.Base_ModBoiler"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wPump",
            "u1",
            "PLR"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wPump",
            "u2",
            "dT_Water"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wPump",
            "dT_Water",
            "dTWater"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wPump",
            "u",
            "y"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.Base_Boiler",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump",
            "sine",
            "const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "u",
            "y"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "u",
            "y"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "y",
            "TCold"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "y",
            "TCold"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "y1",
            "y"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "y1",
            "y"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "y1",
            "dTWater"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "y1",
            "dTWater"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "y1",
            "PLR"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "y1",
            "PLR"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "TCold1",
            "THor"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "TCold1",
            "THor"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "THor",
            "THot"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "THor",
            "THot"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "TCold1",
            "EnergyDemand"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "TCold1",
            "EnergyDemand"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "THot",
            "THot_Boiler"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "THot",
            "THot_Boiler"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "THot_Boiler1",
            "THot"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "THot_Boiler1",
            "THot"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "EnergyDemand1",
            "dTwater"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "EnergyDemand1",
            "dTwater"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "dTwater1",
            "PLR_in"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "dTwater1",
            "PLR_in"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wFeedback",
            "dTwater",
            "dTwater_in"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.BaseClasses.ModularBoiler_base",
            "dTwater",
            "dTwater_in"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.ModularBoiler_base",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.Control_wPump"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wPump",
            "u",
            "PLR"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump",
            "modularBoiler_wPump.u",
            "modularBoiler_wPump.PLR"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wPump",
            "u1",
            "dTWater"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump",
            "modularBoiler_wPump.u1",
            "modularBoiler_wPump.dTWater"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wPump_wFeedback",
            "control_wPump",
            "control_wPump_wFeedback"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_wPump_wFeedback",
            "control_wPump_wFeedback.y1",
            "control_wPump_wFeedback.y_valve"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.Control_wPump_wFeedback",
            "y1",
            "y_valve"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump_wFeedback",
            "modularBoiler_wPump",
            "modularBoiler_wPump_wFeedback"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump_wFeedback",
            "const3",
            "sine"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.Regulation_wPump_wFeedBack",
            "PLR_in1",
            "PLR_mea"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_Regulation_wPump_wFeedback",
            "control_wPump_wFeedback",
            "regulation_wPump_wFeedBack"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedback",
            "modularBoiler_wPump_wFeedback",
            "modularBoiler_Regulation_wPump_wFeedback"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "modularBoiler_Regulation_wPump_wFeedback",
            "modularBoiler_Regulation_wPump_wFeedback_wAdmix"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "sine1",
            "const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "modularBoiler_Regulation_wPump_wFeedback_wAdmix.sine1",
            "modularBoiler_Regulation_wPump_wFeedback_wAdmix.const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_ControlUnity",
            "hierarchicalControl.severalHeatcurcuits",
            "hierarchicalControl.severalHeatCircuits"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.HierarchicalControl",
            "severalHeatcurcuits",
            "severalHeatCircuits"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_ControlUnity",
            "hierarchicalControl.internalControl.severalHeatcurcuits",
            "hierarchicalControl.internalControl.severalHeatCircuits"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_",
            "hierarchicalControl.internalControl.severalHeatcurcuits",
            "hierarchicalControl.internalControl.severalHeatCircuits"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.HierarchicalControl",
            "internalControl.severalHeatcurcuits",
            "internalControl.severalHeatCircuits"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.HierarchicalControl_ModularBoiler.InternalControl",
            "severalHeatcurcuits",
            "severalHeatCircuits"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "modularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "modularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "booleanExpression1",
            "realExpression"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump",
            "const2",
            "dT_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump",
            "const1",
            "PLR_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump_wFeedback",
            "const1",
            "PLR_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump_wFeedback",
            "const2",
            "dT_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_wPump_wFeedback",
            "sine",
            "BouT_sine"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedbac",
            "const1",
            "PLR_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedbac",
            "const2",
            "dT_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedbac",
            "sine",
            "BouT_sine"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedbac",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedback"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "sine",
            "BouT_sine"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "const1",
            "PLR_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "const2",
            "dT_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "const1",
            "PLR_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "const2",
            "dT_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "const3",
            "TCon1_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "const4",
            "TCon2_const"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "sine",
            "BouT_sine"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "sine",
            "ValveSet_sine"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_Regulation_wPump_wFeedback_wAdmix",
            "modularBoiler_Regulation_wPump_wFeedback_wAdmix.sine",
            "modularBoiler_Regulation_wPump_wFeedback_wAdmix.ValveSet_sine"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.Regulation_ModularBoiler",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.BaseClasses.Regulation_ModularBoiler"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.TwoPositionController",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.TwoPositionController_models"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.partialTwoPositionController",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.TwoPositionController"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_",
            "hierarchicalControl.internalControl.twoPositionController_top",
            "hierarchicalControl.internalControl.twoPositionController"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.HierarchicalControl",
            "internalControl.twoPositionController_top",
            "internalControl.twoPositionController"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Control.HierarchicalControl_ModularBoiler.InternalControl",
            "twoPositionController_top",
            "twoPositionController"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "modularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_.hierarchicalControl.internalControl.twoPositionController_top",
            "modularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_.hierarchicalControl.internalControl.twoPositionController"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_",
            "port_b",
            "port_b1"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix",
            "modularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_.port_b",
            "modularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_.port_b1"),

        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix_with_Consumers",
            "modularConsumer",
            "modularConsumer_multiport"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix_with_Consumers",
            "TCon2_const",
            "TCon1"),
        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_HierachicalRegulation_wPump_wFeedback_wAdmix_with_Consumers",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_with_Consumers"),

        item=convertClass(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_HierarchicalRegulation_wPump_wFeedback_wAdmix_",
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.ModularBoiler_multiport"),

        item=convertElement(
            "AixLib.Systems.HydraulicModules.Controller.CtrSimpleConsumer_base",
            "y",
            "y_val"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Controller.CtrSimpleConsumer_base",
            "y_val1",
            "y_pump"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.SimpleConsumer",
            "ctrSimpleConsumer.Q_flow1",
            "ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Controller.CtrSimpleConsumer",
            "Q_flow1",
            "Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Pump",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Feedback",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Pump_Feedback",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.simpleconsumer_1",
            "simpleConsumer_base.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer_base.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_with_Consumers",
            "modularConsumer_multiport.simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "modularConsumer_multiport.simpleConsumer.ctrSimpleConsumer.Q_flow_max"),

        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularConsumer.ModularConsumer",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularConsumer.ModularConsumer_multiport",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.SimpleConsumer",
            "ctrSimpleConsumer.Q_flow1",
            "ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Controller.CtrSimpleConsumer",
            "Q_flow1",
            "Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Pump",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Feedback",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Pump_Feedback",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.simpleconsumer_1",
            "simpleConsumer_base.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer_base.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_with_Consumers",
            "modularConsumer_multiport.simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "modularConsumer_multiport.simpleConsumer.ctrSimpleConsumer.Q_flow_max"),

        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularConsumer.ModularConsumer",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularConsumer.ModularConsumer_multiport",
            "simpleConsumer.ctrSimpleConsumer.Q_flow1",
            "simpleConsumer.ctrSimpleConsumer.Q_flow_max"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.SimpleConsumer",
            "Q_realExp",
            "Q_flow_max_exp"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer",
            "simpleConsumer.Q_realExp",
            "simpleConsumer.Q_flow_max_exp"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Pump",
            "simpleConsumer.Q_realExp",
            "simpleConsumer.Q_flow_max_exp"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Feedback",
            "simpleConsumer.Q_realExp",
            "simpleConsumer.Q_flow_max_exp"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.SimpleConsumer_Pump_Feedback",
            "simpleConsumer.Q_realExp",
            "simpleConsumer.Q_flow_max_exp"),
        item=convertElement(
            "AixLib.Systems.HydraulicModules.Example.simpleconsumer_1",
            "simpleConsumer_base.Q_realExp",
            "simpleConsumer_base.Q_flow_max_exp"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularBoiler.Example.ModularBoiler_with_Consumers",
            "modularConsumer_multiport.simpleConsumer.Q_realExp",
            "modularConsumer_multiport.simpleConsumer.Q_flow_max_exp"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularConsumer.ModularConsumer",
            "simpleConsumer.Q_realExp",
            "simpleConsumer.Q_flow_max_exp"),
        item=convertElement(
            "AixLib.Systems.ModularEnergySystems.Modules.ModularConsumer.ModularConsumer_multiport",
            "simpleConsumer.Q_realExp",
            "simpleConsumer.Q_flow_max_exp")))),
  Documentation(info = "<html><p>
  The free open-source <code>AixLib</code> library is being developed
  for research and teaching purposes. It aims at dynamic simulations of
  thermal and hydraulic systems to develop control strategies for HVAC
  systems and analyse interactions in complex systems. It is used for
  simulations on component, building and city district level. As this
  library is developed mainly for academic purposes, user-friendliness
  and model robustness is not a main task. This research focus thus
  influences the layout and philosophy of the library.
</p>
<p>
  Various connectors of the Modelica Standard Library are used, e.g.
  <code>Modelica.Fluid</code> and <code>Modelica.HeatTransfer</code>.
  These are accompanied by own connectors for simplified hydraulics (no
  <code>fluid.media</code>, incompressible, one phase) , shortwave
  radiation (intensity), longwave radiation (heat flow combined with a
  virtual temperature) and combined longwave radiation and thermal. The
  pressure in the connectors is the total pressure. The used media
  models are simplified from the <code>Modelica.Media</code> library.
  If possible and necessary, components use continuously differentiable
  equations. In general, zero mass flow rate and reverse flow are
  supported.
</p>
<p>
  Most models have been analytically verified. In addition, hydraulic
  components are compared to empirical data such as performance curves.
  High and low order building models have been validated using a
  standard test suite provided by the ANSI/ASHRAE Standard 140 and VDI
  6007 Guideline. The library has only been tested with Dymola.
</p>
<p>
  The web page for this library is <a href=
  \"https://www.github.com/RWTH-EBC/AixLib\">https://www.github.com/RWTH-EBC/AixLib</a>.
  We welcome contributions from different users to further advance this
  library, whether it is through collaborative model development,
  through model use and testing or through requirements definition or
  by providing feedback regarding the model applicability to solve
  specific problems.
</p>
</html>"),
  Icon(coordinateSystem(preserveAspectRatio = false, extent = {{-100, -100}, {100, 100}}), graphics={Bitmap(extent={{-106,-100},{106,100}}, fileName = "modelica://AixLib/Resources/Images/Icon_Modelica_AixLib.png")}));
end AixLib;
