stages:
    - simulate

.CI_simulate_model_job:
    stage: simulate
    before_script:
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate myenv
        - pip install natsort
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - xvfb-run -n 77 python bin/CITests/02_UnitTests/CheckPackages/validatetest.py  --single-package "${lib_package}" --library AixLib -DS 2022 --wh-library IBPSA --filterwhitelist --simulateexamples  
    artifacts:
        when: on_failure
        paths:
            - AixLib/AixLib.${lib_package}-log.txt
            - AixLib/AixLib.${lib_package}-errorlog.txt
        expire_in: 7 day 
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /ci_simulate/
    except:
        refs:
            - external_pull_requests
    retry:
        max: 2
        when: runner_system_failure  
        
CI_simulate_AixLib_Airflow:
    variables:
        lib_package: Airflow
    extends: .CI_simulate_model_job

CI_simulate_AixLib_BoundaryConditions:
    variables:
        lib_package: BoundaryConditions
    extends: .CI_simulate_model_job

CI_simulate_AixLib_Controls:
    variables:
        lib_package: Controls
    extends: .CI_simulate_model_job

CI_simulate_AixLib_Electrical:
    variables:
        lib_package: Electrical
    extends: .CI_simulate_model_job

CI_simulate_AixLib_Fluid:
    variables:
        lib_package: Fluid
    extends: .CI_simulate_model_job

CI_simulate_AixLib_Media:
    variables:
        lib_package: Media
    extends: .CI_simulate_model_job

CI_simulate_AixLib_Systems:
    variables:
        lib_package: Systems
    extends: .CI_simulate_model_job

CI_simulate_AixLib_ThermalZones:
    variables:
        lib_package: ThermalZones
    extends: .CI_simulate_model_job

CI_simulate_AixLib_Utilities:
    variables:
        lib_package: Utilities
    extends: .CI_simulate_model_job

    
.dev_simulate_model_job:
    stage: simulate
    before_script:
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate myenv
        - pip install natsort
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - xvfb-run -n 77 python bin/CITests/02_UnitTests/CheckPackages/validatetest.py  --single-package "${lib_package}" --library AixLib -DS 2022 --wh-library IBPSA --filterwhitelist --simulateexamples
    artifacts:
        when: on_failure
        paths:
            - AixLib/AixLib.${lib_package}-log.txt
            - AixLib/AixLib.${lib_package}-errorlog.txt
        expire_in: 7 day
    only:
        refs:
            - master
            - development
    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~ /ci_update_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_dif_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_correct_html/
            - $CI_COMMIT_MESSAGE  =~ /ci_create_whitelist/
            - $CI_COMMIT_MESSAGE  =~ /Automatic push of CI with new regression reference files. Please pull the new files before push again./
            - $CI_COMMIT_MESSAGE  =~ /New reference files were pushed to this branch. The job was successfully and the newly added files are tested in another commit./
            - $CI_COMMIT_MESSAGE  =~ /ci_show_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_regression_test/
            - $CI_COMMIT_MESSAGE  =~ /ci_check/
            - $CI_COMMIT_MESSAGE  =~ /ci_simulate/
            - $CI_COMMIT_MESSAGE  =~ /ci_create_html_whitelist/
            - $CI_COMMIT_MESSAGE  =~ /ci_html/
            - $CI_COMMIT_MESSAGE  =~ /ci_setting/
    retry:
        max: 2
        when: runner_system_failure

Development_simulate_AixLib_Airflow:
    variables:
        lib_package: Airflow
    extends: .dev_simulate_model_job

Development_simulate_AixLib_BoundaryConditions:
    variables:
        lib_package: BoundaryConditions
    extends: .dev_simulate_model_job

Development_simulate_AixLib_Controls:
    variables:
        lib_package: Controls
    extends: .dev_simulate_model_job

Development_simulate_AixLib_Electrical:
    variables:
        lib_package: Electrical
    extends: .dev_simulate_model_job

Development_simulate_AixLib_Fluid:
    variables:
        lib_package: Fluid
    extends: .dev_simulate_model_job

Development_simulate_AixLib_Media:
    variables:
        lib_package: Media
    extends: .dev_simulate_model_job

Development_simulate_AixLib_Systems:
    variables:
        lib_package: Systems
    extends: .dev_simulate_model_job

Development_simulate_AixLib_ThermalZones:
    variables:
        lib_package: ThermalZones
    extends: .dev_simulate_model_job

Development_simulate_AixLib_Utilities:
    variables:
        lib_package: Utilities
    extends: .dev_simulate_model_job




.simulate_model_job:
    stage: simulate
    before_script:
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate myenv
        - pip install natsort
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - xvfb-run -n 77 python bin/CITests/02_UnitTests/CheckPackages/validatetest.py  --single-package "${lib_package}" --library AixLib -DS 2022 --wh-library IBPSA --filterwhitelist --simulateexamples 
    artifacts:
        when: on_failure
        paths:
            - AixLib/AixLib.${lib_package}-log.txt
            - AixLib/AixLib.${lib_package}-errorlog.txt
        expire_in: 7 day 
    only:
        refs:
            - external_pull_requests

    except:
        variables:
            - $CI_COMMIT_MESSAGE  =~ /ci_update_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_dif_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_correct_html/
            - $CI_COMMIT_MESSAGE  =~ /ci_create_whitelist/
            - $CI_COMMIT_MESSAGE  =~ /Automatic push of CI with new regression reference files. Please pull the new files before push again./
            - $CI_COMMIT_MESSAGE  =~ /New reference files were pushed to this branch. The job was successfully and the newly added files are tested in another commit./
            - $CI_COMMIT_MESSAGE  =~ /ci_show_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_regression_test/
            - $CI_COMMIT_MESSAGE  =~ /ci_check/
            - $CI_COMMIT_MESSAGE  =~ /ci_simulate/
            - $CI_COMMIT_MESSAGE  =~ /ci_create_html_whitelist/
            - $CI_COMMIT_MESSAGE  =~ /ci_html/
            - $CI_COMMIT_MESSAGE  =~ /ci_setting/
        refs:
            - master
            - development

    retry:
        max: 2
        when: runner_system_failure  
        
simulate_AixLib_Airflow:
    variables:
        lib_package: Airflow
    extends: .simulate_model_job

simulate_AixLib_BoundaryConditions:
    variables:
        lib_package: BoundaryConditions
    extends: .simulate_model_job

simulate_AixLib_Controls:
    variables:
        lib_package: Controls
    extends: .simulate_model_job

simulate_AixLib_Electrical:
    variables:
        lib_package: Electrical
    extends: .simulate_model_job

simulate_AixLib_Fluid:
    variables:
        lib_package: Fluid
    extends: .simulate_model_job

simulate_AixLib_Media:
    variables:
        lib_package: Media
    extends: .simulate_model_job

simulate_AixLib_Systems:
    variables:
        lib_package: Systems
    extends: .simulate_model_job

simulate_AixLib_ThermalZones:
    variables:
        lib_package: ThermalZones
    extends: .simulate_model_job

simulate_AixLib_Utilities:
    variables:
        lib_package: Utilities
    extends: .simulate_model_job

    
.simulate_changed_models_job:
    stage: simulate
    before_script:
        - export PIP_CACHE_DIR="/opt/cache/pip"
        - source activate myenv
        - pip install natsort
        - export PYTHONIOENCODING=utf-8 # just in case
    script:
        - git diff --raw --diff-filter=AMT HEAD^1 >  bin/Configfiles/ci_changed_model_list.txt
        - xvfb-run -n 77 python bin/CITests/02_UnitTests/CheckPackages/validatetest.py --single-package "${lib_package}" --library AixLib -DS 2022 -CM --simulateexamples 
    artifacts:
        when: on_failure
        paths:
            - AixLib/AixLib.${lib_package}-log.txt
            - AixLib/AixLib.${lib_package}-errorlog.txt
        expire_in: 7 day
    except:
        refs:
            - external_pull_requests
            - IBPSA_Merge
            - master
            - development
        variables:
            - $CI_COMMIT_MESSAGE  =~ /ci_update_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_dif_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_correct_html/
            - $CI_COMMIT_MESSAGE  =~ /ci_create_whitelist/
            - $CI_COMMIT_MESSAGE  =~ /Automatic push of CI with new regression reference files. Please pull the new files before push again./
            - $CI_COMMIT_MESSAGE  =~ /New reference files were pushed to this branch. The job was successfully and the newly added files are tested in another commit./
            - $CI_COMMIT_MESSAGE  =~ /ci_show_ref/
            - $CI_COMMIT_MESSAGE  =~ /ci_regression_test/
            - $CI_COMMIT_MESSAGE  =~ /ci_check/
            - $CI_COMMIT_MESSAGE  =~ /ci_simulate/
            - $CI_COMMIT_MESSAGE  =~ /ci_create_html_whitelist/
            - $CI_COMMIT_MESSAGE  =~ /ci_html/
            - $CI_COMMIT_MESSAGE  =~ /ci_setting/
    retry:
        max: 2
        when: runner_system_failure

simulate_AixLib_Airflow_changed_models:
    variables:
        lib_package: Airflow
    only:
        changes:
            - AixLib/Airflow/**/*  
    extends: .simulate_changed_models_job

simulate_AixLib_BoundaryConditions_changed_models:
    variables:
        lib_package: BoundaryConditions
    only:
        changes:
            - AixLib/BoundaryConditions/**/*  
    extends: .simulate_changed_models_job

simulate_AixLib_Controls_changed_models:
    variables:
        lib_package: Controls
    only:
        changes:
            - AixLib/Controls/**/*  
    extends: .simulate_changed_models_job

simulate_AixLib_Electrical_changed_models:
    variables:
        lib_package: Electrical
    only:
        changes:
            - AixLib/Electrical/**/*  
    extends: .simulate_changed_models_job

simulate_AixLib_Fluid_changed_models:
    variables:
        lib_package: Fluid
    only:
        changes:
            - AixLib/Fluid/**/*  
    extends: .simulate_changed_models_job

simulate_AixLib_Media_changed_models:
    variables:
        lib_package: Media
    only:
        changes:
            - AixLib/Media/**/*  
    extends: .simulate_changed_models_job

simulate_AixLib_Systems_changed_models:
    variables:
        lib_package: Systems
    only:
        changes:
            - AixLib/Systems/**/*  
    extends: .simulate_changed_models_job

simulate_AixLib_ThermalZones_changed_models:
    variables:
        lib_package: ThermalZones
    only:
        changes:
            - AixLib/ThermalZones/**/*  
    extends: .simulate_changed_models_job

simulate_AixLib_Utilities_changed_models:
    variables:
        lib_package: Utilities
    only:
        changes:
            - AixLib/Utilities/**/*  
    extends: .simulate_changed_models_job

