library_root = ""
dir = "ci"
naming_guideline_file = "naming_guideline.toml"

[result]
dir = "result"
whitelist_dir = "ci_whitelist"
plot_dir = "charts"
syntax_dir = "syntax"
regression_dir = "regression"
check_result_dir = "Dymola_check"
naming_violation_file = "naming_violations.txt"

[ci_files]
dir = "Configfiles"
exit_file = "exit.sh"
new_create_ref_file = "ci_new_created_reference.txt"
changed_file = "ci_changed_model_list.txt"
ref_file = "ci_reference_list.txt"

[whitelist]
dir = "whitelist"
dymola_check_file = "dymola_check_whitelist.txt"
dymola_simulate_file = "dymola_simulate_whitelist.txt"
ibpsa_file = "ibpsa_whitelist.txt"
dymola_reference_file = "dymola_reference_whitelist.txt"
om_check_file = "om_check_whitelist.txt"
om_simulate_file = "om_simulate_whitelist.txt"

[artifacts]
dir = "artifacts"
library_ref_results_dir = "Resources/ReferenceResults/Dymola"
library_resource_dir = "Resources/Scripts/Dymola"

[interact]
dir = "interact_CI"
show_ref_file = "show_ref.txt"
update_ref_file = "update_ref.txt"

[plots]
chart_dir = "charts"
templates_chart_dir = "MoCITempGen/templates/google_templates"
templates_chart_file = "MoCITempGen/templates/google_templates/google_chart.txt"
templates_index_file = "MoCITempGen/templates/google_templates/index.txt"
templates_layout_file = "MoCITempGen/templates/google_templates/layout_index.txt"
