# You can adjust the sequence of the stages to your needs
stages:
    - model_check
    - create_model_whitelist
    - RegressionTest
    - Ref_Check
    - plot_ref
    - prepare
    - HTML_Check
    - create_html_whitelist
    - open_PR
    - OM_model_check
    - OM_simulate
    - merge
    - update_whiteList
    - Style_check
    - simulate
    - create_example_whitelist
    - deploy

variables:
    Github_Repository: RWTH-EBC/AixLib
    GITLAB_Page:  https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/AixLib

include:
    - 'bin/ci-tests/scripts/unit_tests/check_model.gitlab-ci.yml'  
    - 'bin/ci-tests/scripts/unit_tests/regression_test.gitlab-ci.yml'  
    - 'bin/ci-tests/scripts/syntax_tests/html_check.gitlab-ci.yml'  
    - 'bin/ci-tests/scripts/unit_tests/check_OM_model.gitlab-ci.yml'  
    - 'bin/ci-tests/scripts/unit_tests/simulate_OM_model.gitlab-ci.yml'  
    - 'bin/ci-tests/scripts/deploy/IBPSA_Merge.gitlab-ci.yml'  
    - 'bin/ci-tests/scripts/syntax_tests/style_check.gitlab-ci.yml'  
    - 'bin/ci-tests/scripts/deploy/gitlab_pages.gitlab-ci.yml'  
    - 'bin/ci-tests/scripts/unit_tests/simulate_model.gitlab-ci.yml'  
