############################################################
# Makefile for the regression tests that are run on travis
############################################################
ROOT = ../../../..

test-documentation:
	(cd $(ROOT)/AixLib; Resources/Scripts/runUnitTests.py --validate-html-only)
