within AixLib.Fluid.HeatPumps.ModularReversible.Data.TableDataSDF.TableData3D;
package VCLibPy "Package containing links to 3D-SDF tables generated by VCLibPy"
  extends Modelica.Icons.MaterialPropertiesPackage;

end VCLibPy;
