#!/bin/bash
image: registry.git.rwth-aachen.de/ebc/ebc_intern/dymola-docker:miniconda-latest

stages:
    - deleteBranch
   

    
Delte_merge_Branches:
    stage: deleteBranch
    only:
        - /^feature\/*/
    services:
        -  docker
    before_script:
        - sudo apt-get install jq -y
    script:
       # Newbranch=${Newbranch#${Praefix_Branch}}
       # TARGET_BRANCH=${TARGET_BRANCH#${Praefix_Branch}}
       - sudo chmod +x bin/06_Configfiles/delete_merged_branches.sh
       - git config --global user.email "${GITLAB_USER_EMAIL}"
       - git config --global user.name  "${GITLAB_USER_NAME}" 
       - bin/06_Configfiles/delete_merged_branches.sh
    
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^Merge pull request/
